### ISSUE TITLE
AXCustomContent localizable strings

### ISSUE THREAD

**Issue by mattgarrish** [w3c/dpub-aam#18]
The question was raised in https://github.com/w3c/dpub-aam/pull/15#issuecomment-1371103482 about whether the new AXCustomContent strings are localizable.

I noticed that the core AAM document has this note:

> User agent should return a user-presentable, localized string value for the AXRoleDescription.

@cookiecrook, @aleventhal  do you think this could be solved by adding this note to the DPUB document and also have it reference AXCustomContent?

> User agent should return a user-presentable, localized string value for the AXRoleDescription and AXCustomContent.

**Comment by aleventhal** [comment]
Although only part of AXCustomContent is localized, correct?

For example:
```
{ label: "type", value: "abstract" }
```

I assume only the value field is localized.

**Comment by mattgarrish** [comment]
> I assume only the value field is localized.

Ya, I was trying to avoid saying value twice. It's probably not necessary to say "string value" for the description, so what if we move it to describe the AXCC field:

> User agents should return a user-presentable, localized string for the AXRoleDescription and the AXCustomContent value.

**Comment by aleventhal** [comment]
SGTM

**Comment by mattgarrish** [comment]
Closing with https://github.com/w3c/dpub-aam/pull/20
