### ISSUE TITLE
How to expose doc-pageheader, doc-pagefooter

### ISSUE THREAD

**Issue by aleventhal** [w3c/dpub-aam#3]
For doc-pageheader, doc-pagefooter, each API needs to determine how it wants to expose them.
For ATK, IA2 -- do we think we'll want new roles, or just rely on the xml-roles object attribute?
For the AX API, should we use a subrole?

Here's the DPUB-ARIA pull request.https://github.com/w3c/dpub-aria/pull/28

**Comment by mattgarrish** [comment]
Closing this with #4
