### ISSUE TITLE
Getting error when generating using labs

### ISSUE THREAD

**Issue by jnurthen** [w3c/dpub-aam#6]
## Important info

- URL to affected spec: https://github.com/w3c/dpub-aam
- ReSpec version: Click the ReSpec pill in top-right corner (e.g., 25.12.0).
- [ ] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**
Got error:
```Bash
{"error":"\n😭  Sorry, there was an error generating the HTML. Please report this issue!\nSpecification: https://raw.githack.com/w3c/dpub-aam/main/index.html?publishDate=2021-07-21\nReSpec version: 25.6.0\nFile a bug: https://github.com/w3c/respec/\nError: Error: Evaluation failed: Timeout: document.respec.ready didn't resolve in 28725ms.\n    at ExecutionContext._evaluateInternal (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async ExecutionContext.evaluate (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)\n    at async generateHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:276:12)\n    at async toHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:92:18)\n    at async Object.generate [as respec] (/u/spec-generator/generators/respec.js:14:44)\n    at async /u/spec-generator/server.js:203:44\n"}
```

**Expected behavior (e.g., it shouldn't crash):**
Should work

**Optional, steps to reproduce:**
Run https://labs.w3.org/spec-generator/?type=respec&url=https://raw.githack.com/w3c/dpub-aam/main/index.html
1

**Comment by jnurthen** [comment]
@michael-n-cooper why is the PR using that version of the file? The version in the PR has been modified and doesn't have that issue. I tried modifying the Travis script to be like the other repositories but am really not sure what that curl line is actually doing. Why is it referencing the main branch rather than the PR branch?

**Comment by jnurthen** [comment]
@marcoscaceres thanks. Seems like the script running on PRs is useless as it is building using the previous version so I have turned off the script for PRs in travis.

**Comment by marcoscaceres** [comment]
Thanks for the update @jnurthen. Let me know if I can be of any additional help.
